let 회원정보 = [
  {
    _id: "61a6e15dda7d04dc60195de5",
    index: 0,
    guid: "ea23e66e-d3c9-4ff9-a7d1-fe1a1257389c",
    isActive: false,
    balance: "$1,857.70",
    picture: "http://placehold.it/32x32",
    age: 28,
    eyeColor: "brown",
    name: "Elnora Norris",
    gender: "female",
    company: "ENERVATE",
    email: "elnoranorris@enervate.com",
    phone: "+1 (800) 441-3876",
    address: "519 Locust Avenue, Benson, Florida, 4509",
    about:
      "Aliqua exercitation nulla amet culpa dolore ex fugiat aliqua. Irure nostrud adipisicing elit culpa esse nostrud duis. Nulla nisi eu nisi sunt cillum veniam excepteur do cupidatat irure non id tempor fugiat.\r\n",
    registered: "2015-09-15T06:32:12 -09:00",
    latitude: -78.8213,
    longitude: -104.94222,
    tags: ["ad", "Lorem", "aliquip", "laborum", "sit", "eu", "non"],
    friends: [
      {
        id: 0,
        name: "Clark Kidd",
      },
      {
        id: 1,
        name: "Traci Velazquez",
      },
      {
        id: 2,
        name: "Hammond Hahn",
      },
    ],
    greeting: "Hello, Elnora Norris! You have 1 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "61a6e15d861b63f1e84428c6",
    index: 1,
    guid: "134827df-f66e-440b-a849-84464f4dc0ce",
    isActive: false,
    balance: "$2,768.85",
    picture: "http://placehold.it/32x32",
    age: 26,
    eyeColor: "green",
    name: "Alejandra Rowland",
    gender: "female",
    company: "VITRICOMP",
    email: "alejandrarowland@vitricomp.com",
    phone: "+1 (894) 544-3302",
    address: "592 Harrison Avenue, Nutrioso, Minnesota, 1732",
    about:
      "Eu eu culpa proident fugiat esse magna laboris fugiat tempor id. Amet dolor culpa fugiat aute esse ad nulla exercitation pariatur. Esse ut officia exercitation id sint fugiat laboris in.\r\n",
    registered: "2017-04-30T03:13:08 -09:00",
    latitude: 43.543439,
    longitude: -80.084858,
    tags: ["aliqua", "commodo", "officia", "fugiat", "eu", "labore", "enim"],
    friends: [
      {
        id: 0,
        name: "Lisa Rios",
      },
      {
        id: 1,
        name: "Jeannette Russo",
      },
      {
        id: 2,
        name: "Simon Rogers",
      },
    ],
    greeting: "Hello, Alejandra Rowland! You have 4 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "61a6e15dffe98eff5052bffe",
    index: 2,
    guid: "8348158f-827c-42d5-8952-4d1b0ce8d67a",
    isActive: false,
    balance: "$1,517.81",
    picture: "http://placehold.it/32x32",
    age: 33,
    eyeColor: "green",
    name: "Eugenia Bullock",
    gender: "female",
    company: "SCENTY",
    email: "eugeniabullock@scenty.com",
    phone: "+1 (939) 515-2815",
    address: "581 Wilson Avenue, Wright, Guam, 4742",
    about:
      "Nisi in sit nostrud consequat commodo. Voluptate esse duis amet consectetur aliqua laborum cupidatat excepteur tempor enim. Ut minim sit quis mollit do ipsum proident commodo. Sint mollit laborum nulla eiusmod velit elit ad non enim duis ullamco.\r\n",
    registered: "2016-02-19T09:18:33 -09:00",
    latitude: -2.883379,
    longitude: 99.902328,
    tags: ["tempor", "nulla", "anim", "esse", "non", "consectetur", "eiusmod"],
    friends: [
      {
        id: 0,
        name: "Small Knowles",
      },
      {
        id: 1,
        name: "Flora Boyd",
      },
      {
        id: 2,
        name: "Lesa Flynn",
      },
    ],
    greeting: "Hello, Eugenia Bullock! You have 2 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "61a6e15d3df5c5c6f62a7739",
    index: 3,
    guid: "3871030b-4642-4985-912f-199b5797da8e",
    isActive: true,
    balance: "$3,154.19",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "green",
    name: "Gladys Rivas",
    gender: "female",
    company: "ZILLAR",
    email: "gladysrivas@zillar.com",
    phone: "+1 (836) 515-2543",
    address: "196 Cumberland Street, Lowgap, Louisiana, 2050",
    about:
      "Ipsum reprehenderit duis fugiat esse qui consectetur qui occaecat mollit laborum ipsum. Consequat non eiusmod consectetur esse ex anim sint. Et consectetur nostrud do esse ad occaecat enim aute. Tempor officia duis in ex adipisicing minim. Dolor anim nostrud pariatur labore.\r\n",
    registered: "2019-12-03T01:09:21 -09:00",
    latitude: 32.431458,
    longitude: 30.377648,
    tags: [
      "sunt",
      "irure",
      "voluptate",
      "fugiat",
      "consequat",
      "velit",
      "fugiat",
    ],
    friends: [
      {
        id: 0,
        name: "Hayden Roach",
      },
      {
        id: 1,
        name: "Nolan Armstrong",
      },
      {
        id: 2,
        name: "Marcie Valdez",
      },
    ],
    greeting: "Hello, Gladys Rivas! You have 9 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "61a6e15d8e4bd9d343e667c9",
    index: 4,
    guid: "ebfd5ba8-3c95-4ba8-b02f-969b556d61b3",
    isActive: false,
    balance: "$2,712.98",
    picture: "http://placehold.it/32x32",
    age: 40,
    eyeColor: "green",
    name: "Jami Wall",
    gender: "female",
    company: "NAXDIS",
    email: "jamiwall@naxdis.com",
    phone: "+1 (865) 431-2016",
    address: "947 Hunterfly Place, Elrama, Kentucky, 9615",
    about:
      "Consequat in deserunt deserunt excepteur proident laboris nulla qui aliquip ea commodo non ea. Non dolore nostrud consequat amet nostrud sunt adipisicing minim officia magna est eiusmod. Incididunt magna reprehenderit enim nulla enim ea amet amet eiusmod tempor veniam irure Lorem. Aliquip nisi consectetur veniam nisi nostrud elit et ullamco mollit labore eiusmod exercitation. Aute ex quis occaecat consequat.\r\n",
    registered: "2019-12-04T10:58:36 -09:00",
    latitude: 72.490957,
    longitude: 126.426266,
    tags: ["ad", "occaecat", "officia", "aliqua", "laborum", "in", "id"],
    friends: [
      {
        id: 0,
        name: "Gomez Sloan",
      },
      {
        id: 1,
        name: "Decker Perry",
      },
      {
        id: 2,
        name: "Finch Lambert",
      },
    ],
    greeting: "Hello, Jami Wall! You have 9 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "61a6e15d2a537762eabc5f77",
    index: 5,
    guid: "151af69c-2591-4b3d-8d21-a6b53cd5ed26",
    isActive: true,
    balance: "$2,591.84",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "green",
    name: "Katy Carver",
    gender: "female",
    company: "IPLAX",
    email: "katycarver@iplax.com",
    phone: "+1 (867) 547-3234",
    address: "457 Jardine Place, Rivera, Delaware, 4341",
    about:
      "Incididunt consectetur veniam ea anim adipisicing est mollit ea deserunt aute. Adipisicing sint sint ipsum duis consectetur id excepteur. Tempor excepteur aute occaecat occaecat consequat dolor amet in consectetur minim cupidatat.\r\n",
    registered: "2016-04-03T01:45:32 -09:00",
    latitude: -4.325652,
    longitude: -50.113045,
    tags: [
      "aute",
      "deserunt",
      "adipisicing",
      "sint",
      "minim",
      "aliqua",
      "consequat",
    ],
    friends: [
      {
        id: 0,
        name: "Clarke Barron",
      },
      {
        id: 1,
        name: "Jodi Solomon",
      },
      {
        id: 2,
        name: "Merle Cruz",
      },
    ],
    greeting: "Hello, Katy Carver! You have 9 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "61a6e15d62a3a365eac44f40",
    index: 6,
    guid: "a9428f2e-40d6-4351-b824-ee84ab69d7c1",
    isActive: true,
    balance: "$2,319.56",
    picture: "http://placehold.it/32x32",
    age: 20,
    eyeColor: "green",
    name: "Rivers Kelly",
    gender: "male",
    company: "ECRAZE",
    email: "riverskelly@ecraze.com",
    phone: "+1 (964) 548-2730",
    address: "349 Karweg Place, Woodlands, Michigan, 4086",
    about:
      "Et exercitation officia labore eiusmod sunt in officia quis nisi laboris ad veniam. Incididunt labore laborum sit sint mollit aliqua esse aliqua ipsum sint ipsum dolor ea. Elit ut magna anim ipsum minim non cupidatat veniam quis do incididunt non. Ad reprehenderit do est adipisicing eu et pariatur fugiat fugiat. Aute cupidatat quis sit velit ullamco nulla adipisicing tempor est laborum magna nostrud laboris.\r\n",
    registered: "2021-01-03T10:23:05 -09:00",
    latitude: 15.31584,
    longitude: 57.925924,
    tags: ["sunt", "amet", "quis", "est", "enim", "consectetur", "consectetur"],
    friends: [
      {
        id: 0,
        name: "Angelia Waller",
      },
      {
        id: 1,
        name: "Battle Shannon",
      },
      {
        id: 2,
        name: "Karin Richardson",
      },
    ],
    greeting: "Hello, Rivers Kelly! You have 2 unread messages.",
    favoriteFruit: "banana",
  },
];

console.log(회원정보[0].friends);
